PCWeb/Models/Source/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PCWeb.Models
{
    public class Contact
    {
        [DisplayName("STT")]
        public int ContactId { get; set; }
        [DisplayName("Họ và tên")]
        [Required(ErrorMessage = "Họ và tên không được để trống")]
        public string ContactName { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        public string ContactPhone { get; set; }
        [DisplayName("Địa chi")]
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        public string ContactAddress { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email không được để trống")]
        public string ContactEmail { get; set; }
        [DisplayName("Ghi chú")]
        [Required(ErrorMessage = "Ghi chú không được để trống")]
        public string ContactNote { get; set; }
    }
}

PCWeb/Areas/Admin/Controllers/ContactController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PCWeb.Data;
using PCWeb.Models;

namespace PCWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator, Staff")]
    public class ContactController : Controller
    {
        private readonly DataContext dataContext;
        public ContactController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        public IActionResult Index()
        {
            var contactList = dataContext.Contacts.Select(p => p).ToList();
            return View(contactList);
        }
        public IActionResult Detail(int id)
        {
            var contact = dataContext.Contacts.FirstOrDefault(p => p.ContactId == id);
            return View(contact);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Contact oldContact = dataContext.Contacts.FirstOrDefault(p => p.ContactId == id);
            return View(oldContact);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            Contact contact = dataContext.Contacts.FirstOrDefault(p => p.ContactId == id);
            dataContext.Contacts.Remove(contact);
            dataContext.SaveChanges();
            return RedirectToAction("Index", "Contact");
        }
    }
}

PCWeb/Areas/Admin/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PCWeb.Data;
using PCWeb.Models.Name;
using PCWeb.Models.Source;

namespace PCWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator, Staff")]
    public class HomeController : Controller
    {
        private readonly DataContext dataContext;
        public HomeController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var product = dataContext.Products.Select(p => p).ToList();
            var laptop = dataContext.Laptops.Select(p => p).ToList();
            var pc = dataContext.PCs.Select(p => p).ToList();
            var account = dataContext.Users.Select(p => p).ToList();
            List<Product> productLaptop = new List<Product>();
            List<Product> productPC = new List<Product>();
            List<LaptopCategory> laptopCategories = new List<LaptopCategory>();
            List<PCCategory> pcCategories = new List<PCCategory>();
            foreach (var item in laptop)
            {
                Product newLaptop = dataContext.Products.FirstOrDefault(p => p.ProductId == item.ProductId);
                productLaptop.Add(newLaptop);
                LaptopCategory laptopCategory = dataContext.LaptopCategories.FirstOrDefault(p => p.LaptopCategoryId == item.LaptopCategoryId);
                laptopCategories.Add(laptopCategory);
            }
            foreach (var item in pc)
            {
                Product newpc = dataContext.Products.FirstOrDefault(p => p.ProductId == item.ProductId);
                productPC.Add(newpc);
                PCCategory pcCategory = dataContext.PCCategories.FirstOrDefault(p => p.PCCategoryId == item.PCCategoryId);
                pcCategories.Add(pcCategory);
            }
            ViewBag.Product = product.Count();
            ViewBag.Laptop = laptop.Count();
            ViewBag.PC = pc.Count();
            ViewBag.Account = account.Count();
            ViewBag.ListLaptop = laptop;
            ViewBag.ListPC = pc;
            return View();
        }
    }
}

PCWeb/Controllers/DetailController.cs
using Microsoft.AspNetCore.Mvc;
using PCWeb.Data;
using PCWeb.Models.Name;
using PCWeb.Models.Root;
using PCWeb.Models.Source;
using System.Linq;
namespace PCWeb.Controllers
{
    public class DetailController : Controller
    {
        private readonly DataContext dataContext;
        public DetailController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        public IActionResult Index(int id)
        {
            Product product = dataContext.Products.FirstOrDefault(p => p.ProductId == id);
            Brand brand = dataContext.Brands.FirstOrDefault(p => p.BrandId == product.BrandId);
            if (product.CategoryId == 1)
            {
                Laptop laptop = dataContext.Laptops.FirstOrDefault(p => p.ProductId == product.ProductId);
                if (laptop == null)
                    ViewBag.Status = 1;
                else
                {
                    ViewBag.Laptop = laptop;
                    LaptopCategory laptopCategory = dataContext.LaptopCategories.FirstOrDefault(p => p.LaptopCategoryId == laptop.LaptopCategoryId);
                    ViewBag.Category = laptopCategory.LaptopCategoryName;
                }
                
            }
            else
            {
                PC pc = dataContext.PCs.FirstOrDefault(p => p.ProductId == product.ProductId);
                if (pc == null)
                    ViewBag.Status = 1;
                else
                {
                    ViewBag.PC = pc;
                    PCCategory pCCategory = dataContext.PCCategories.FirstOrDefault(p => p.PCCategoryId == pc.PCCategoryId);
                    ViewBag.Category = pCCategory.PCCategoryName;
                }
                
            }
            return View(product);
        }
    }
}

PCWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PCWeb.Data;
using PCWeb.Models;
using System.Diagnostics;
using System.Linq;

namespace PCWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataContext dataContext;
        public HomeController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        public IActionResult Index()
        {
            var item = dataContext.Products.ToList();
            var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
            var itemPC = dataContext.Products.Where(p => p.CategoryId == 2).ToList();
            var laptopCategory = dataContext.LaptopCategories.Select(p => p).ToList();
            var pcCategory = dataContext.PCCategories.Select(p => p).ToList();
            ViewBag.LaptopCategory = laptopCategory;
            ViewBag.PCCategory = pcCategory;
            ViewBag.PC = itemPC;
            ViewBag.Laptop = itemLaptop;
            return View(item);
        }
        public IActionResult Product()
        {
            var item = dataContext.Products.Select(p => p).ToList();
            return View(item);
        }
        public IActionResult Search(string search)
        {
            var query = dataContext.Products.Where(p => p.ProductName.Contains(search)).ToList();
            if (!string.IsNullOrEmpty(search))
                return View(query);
            return RedirectToAction("Index");
        }
        public IActionResult Intro()
        {
            return View();
        }
        public IActionResult News()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Contact(Contact contact)
        {
            if(ModelState.IsValid)
            {
                Contact newContact = new Contact
                {
                    ContactAddress = contact.ContactAddress,
                    ContactEmail = contact.ContactEmail,
                    ContactName = contact.ContactName,
                    ContactNote = contact.ContactNote,
                    ContactPhone = contact.ContactPhone
                };
                dataContext.Contacts.Add(newContact);
                dataContext.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
                return View(contact);
        }
        public IActionResult Privacy()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PCWeb/Views/Home/Contact.cshtml
@model PCWeb.Models.Contact
@{
    ViewData["Title"] = "Liên hệ";
}
<br />
<h2 class="text-center">Góp ý</h2>
<br />
<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Contact" method="post" asp-controller="Home" asp-area="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <label asp-for="ContactName" class="control-label col-md-3"></label>
                <div class="col-md-9">
                    <input asp-for="ContactName" class="form-control" />
                </div>

                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="ContactEmail" class="control-label col-md-3"></label>
                <div class="col-md-9">
                    <input asp-for="ContactEmail" class="form-control" />
                </div>
                <span asp-validation-for="ContactEmail" class="text-danger"> </span>
            </div>
            <div class="form-group row">
                <label asp-for="ContactAddress" class="control-label col-md-3"></label>
                <div class="col-md-9">
                    <input asp-for="ContactAddress" class="form-control" />
                </div>

                <span asp-validation-for="ContactAddress" class="text-danger"> </span>
            </div>
            <div class="form-group row">
                <label asp-for="ContactPhone" class="control-label col-md-3"></label>
                <div class="col-md-9">
                    <input asp-for="ContactPhone" class="form-control" />
                </div>

                <span asp-validation-for="ContactPhone" class="text-danger"> </span>
            </div>
            <div class="form-group row">
                <label asp-for="ContactNote" class="control-label col-md-3"></label>
                <div class="col-md-9">
                    <textarea asp-for="ContactNote" class="form-control"></textarea>
                </div>
                <span asp-validation-for="ContactNote" class="text-danger"> </span>
            </div>
            <div class="form-group row justify-content-center">
                <input type="submit" value="Tạo tài khoản" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

PCWeb/Views/Home/Intro.cshtml
@{
    ViewData["Title"] = "Giới thiệu";
}
<br />
<br />
<div id="aboutform">
    <div class="row">
        <div class="card">
            <img src="~/images/logoaboutus.jpg" style="width: 100%;" />
        </div>
    </div>
    <br />
    <h2 style="text-align:center">Đôi điều về chúng tôi</h2>
    <div class="row">
        <p style="text-align:justify">
            Laptop 123 chuyên cung cấp các sản phẩm laptop chính hãng nhập khẩu US, UK, Japan với hình thức đẹp nhất và chất lượng nhất.

            Sau bao năm cung cấp sản phẩm cho khách hàng chúng tôi hiểu rằng con đường phát triển vững chắc nhất cho đến thời điểm hiện tại là mang đến cho khách hàng những sản phẩm chất lượng ( đặc biệt là được chọn lọc một cách kỹ càng) giá thành phù hợp, bên cạnh đó là chế độ hậu mãi và dịch vụ chăm sóc khách hàng sau bán hàng một cách tốt nhất. Chúng tôi luôn đặt ” UY TÍN ” lên hàng đầu trên mọi mặt hàng kinh doanh tại Laptop 123.

            Với trách nhiệm bảo hành và quyền lợi của Khách hàng, chúng tôi luôn cam kết tát cả các sản phẩm bán ra đều đạt chất lượng tiêu chuẩn ,bản hành dài hạn , 1 đổi 1 miễn phí trong 10 ngày đầu tiên không cần lý do, hỗ trợ khách hàng với những gói bảo hàng 6 tháng đến 1 năm tùy theo yêu cầu of khách hàng. Vệ sinh, hỗ trợ phần mềm laptop trọn đời.
        </p>
        <div class="column">
            <div class="card">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1165.260540992413!2d106.6669191900047!3d10.776525280657173!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752edb0902f141%3A0x9bdc435c85c0033e!2zODI4IFPGsCBW4bqhbiBI4bqhbmgsIFBoxrDhu51uZyAxMiwgUXXhuq1uIDEwLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1591425758439!5m2!1sen!2s" width="1100" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>
    </div>
    <br />
</div>

PCWeb/Views/Home/News.cshtml
@{
    ViewData["Title"] = "Tin tức";
}
<br />
<br />
<h2 class="text-center">Tin khuyến mãi</h2>
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-10 mx-auto" style="text-align:justify;">
                <h1 style="text-align:center; color:red;">
                    TỔNG HỢP KHUYẾN MÃI PC GAMING 2020
                </h1>
                <h2 class="section-heading">1/ Quà tặng khuyến mãi khi build cấu hình GVN Armin 1050Ti :</h2>

                <p>
                    - Tai nghe Plantronics RIG 500 Trị giá 1.490.000VNĐ
                </p>
                <p>
                    - Bàn Phím Dare-U DK87 TKL Trị giá 590.000VND
                </p>
                <p>
                    - Chuột Gaming 1stPlayer BS300 Trị giá 390.000 VND
                </p>
                <p>
                    - Tặng Lót Chuột hình PUBG Extended Trị giá 150.000 VND
                </p>

                <a>
                    <img class="img-fluid" src="~/Images/sale1.png">
                </a>
                <br />
                <br />
                <h2 class="section-heading">2/ Quà tặng khuyến mãi khi build cấu hình GVN Eragon 1050Ti :</h2>

                <p>
                    - Tai nghe Plantronics RIG 500 Trị giá 1.490.000VNĐ
                </p>
                <p>
                    - Bàn Phím Dare-U DK87 TKL Trị giá 590.000VND
                </p>
                <p>
                    - Chuột Gaming 1stPlayer BS300 Trị giá 390.000 VND
                </p>
                <p>
                    - Tặng Lót Chuột hình PUBG Extended Trị giá 150.000 VND
                </p>

                <a>
                    <img class="img-fluid" src="~/Images/sale2.png">
                </a>
                <br />
                <br />
                <h2 class="section-heading">3/ Quà tặng khuyến mãi khi build cấu hình GVN Chopper 1070Ti :</h2>

                <p>
                    - Tai nghe Plantronics RIG 500 Trị giá 1.490.000VNĐ
                </p>
                <p>
                    - Tặng Bàn phím Steelseries Apex M100 Trị giá 890.000 VND
                </p>
                <p>
                    - Chuột Gaming Logitech G102 Trị giá 400.000VNĐ
                </p>
                <p>
                    - Tặng Lót Chuột  hình PUBG Extended Trị giá 150.000 VND
                </p>

                <a>
                    <img class="img-fluid" src="~/Images/sale3.jpg">
                </a>

            </div>
        </div>
    </div>
</article>
<br />

PCWeb/Views/Home/Search.cshtml
@using PCWeb.Models.Source
@{
    ViewData["Title"] = "Kết quả tìm kiếm";
}

@model List<Product>
<br />
<h3>Kết quả tìm kiếm</h3>
<br />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card mb-5 card-info">
                <a asp-controller="Detail"
                   asp-action="Index" asp-route-id="@item.ProductId" asp-route-name="@item.ProductName">
                    <img class="card-img-top card-img"
                         src="~/images/@item.ProductImage" alt="@item.ProductName">
                </a>
                <div class="card-body">
                    <h4 class="card-title">
                        @item.ProductName
                    </h4>
                    <p class="card=text">
                        @item.ProductPrice.ToString("0,0") đ
                    </p>
                </div>
            </div>
        </div>
    }
</div>