PCWeb/Models/Source/Category.cs
using PCWeb.Models.Source;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace PCWeb.Models
{
    public class Category
    {
        [DisplayName("STT")]
        public int CategoryId { get; set; }
        [DisplayName("Tên danh mục")]
        public string CategoryName { get; set; }
        public List<Product> Products { get; set; }
    }
}

PCWeb/Areas/Admin/Controllers/ComponentController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PCWeb.Data;
using PCWeb.Models.Name;
using PCWeb.Models.Source;

namespace PCWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator, Staff")]
    public class ComponentController : Controller
    {
        private readonly DataContext dataContext;
        public ComponentController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }

        public IActionResult Index()
        {
            var item = dataContext.PCComponents.ToList();
            List<Product> pc = new List<Product>();
            List<ComponentCategory> componentCategories = new List<ComponentCategory>();
            foreach (var item2 in item)
            {
                ComponentCategory componentCategory = dataContext.ComponentCategories.FirstOrDefault(p => p.ComponentCategoryId == item2.ComponentCategoryId);
                Product product = dataContext.Products.FirstOrDefault(p => p.ProductId == item2.ProductId);
                pc.Add(product);
            }
            return View(item);
        }
        [HttpGet]
        public IActionResult Add()
        {
            PCComponent pcComponent = new PCComponent();
            var product = dataContext.Products.Where(p => p.CategoryId == 3).ToList();
            var name = dataContext.PCComponents.ToList();
            List<Product> itemSelected = product;
            foreach (var item in name)
            {
                Product query = dataContext.Products.FirstOrDefault(p => p.ProductId == item.ProductId);
                itemSelected.Remove(query);
            }
            ViewBag.Selected = new SelectList(itemSelected, "ProductId", "ProductName");
            var category = dataContext.ComponentCategories.Select(p => p).ToList();
            ViewBag.Category = new SelectList(category, "ComponentCategoryId", "ComponentCategoryName");
            return View(pcComponent);
            
        }
        [HttpPost]
        public IActionResult Add(PCComponent pcComponent)
        {
            if(ModelState.IsValid)
            {
                var query = dataContext.Products.Find(pcComponent.ProductId);
                PCComponent component = new PCComponent
                {
                    ProductId = pcComponent.ProductId,
                    ComponentCategoryId = pcComponent.ComponentCategoryId,
                    PCComponentName = query.ProductName
                };
                dataContext.PCComponents.Add(component);
                dataContext.SaveChanges();
                return RedirectToAction("Index", "Component");
            }
            else
            {
                var item = dataContext.Products.Where(p => p.CategoryId == 3).ToList();
                ViewBag.Selected = new SelectList(item, "ProductId", "ProductName");
                var component = dataContext.ComponentCategories.ToList();
                ViewBag.Category = new SelectList(component, "ComponentCategoryId", "ComponentCategoryName");
                return View(pcComponent);
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            PCComponent component = dataContext.PCComponents.FirstOrDefault(p => p.PCComponentId == id);
            return View(component);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            PCComponent component = dataContext.PCComponents.FirstOrDefault(p => p.PCComponentId == id);
            dataContext.PCComponents.Remove(component);
            dataContext.SaveChanges();
            return RedirectToAction("Index", "Component");
        }
        public IActionResult Category()
        {
            return View();
        }
    }
}

PCWeb/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Mvc;
using PCWeb.Data;
using PCWeb.Helper;
using PCWeb.Models.Root;
using PCWeb.Models.Source;
using System.Collections.Generic;
using System.Linq;

namespace PCWeb.Controllers
{
    public class LaptopController : Controller
    {
        private readonly DataContext dataContext;
        private const string KeyCPU = "cpuList";
        private const string KeyBrand = "brandList";
        private const string KeyPrice = "priceList";
        public LaptopController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        public IActionResult Index()
        {
            var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
            return View(itemLaptop);
        }
        public IActionResult Category(int id)
        {
            var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
            var laptops = new List<Laptop>();
            var result = new List<Product>();
            foreach (var item in itemLaptop)
            {
                Laptop laptop = dataContext.Laptops.FirstOrDefault(p => p.ProductId == item.ProductId && p.LaptopCategoryId == id);
                laptops.Add(laptop);
            }
            foreach (var item in laptops)
            {
                if (item != null)
                {
                    Product product = dataContext.Products.FirstOrDefault(p => p.ProductId == item.ProductId);
                    result.Add(product);
                }
            }
            ViewBag.LaptopCategory = dataContext.LaptopCategories.Find(id).LaptopCategoryName;
            if (result.Count > 0)
                return View(result.ToList());
            else
                return View();
        }
        public IActionResult FilterCPUMain(string cpu)
        {
            return View("Index", FilterCPU(cpu));
        }
        public IActionResult FilterBrandMain(string brand)
        {
            return View("Index", FilterBrand(brand));
        }
        public IActionResult FilterPriceMain(string price)
        {
            return View("Index", FilterPrice(price));
        }
        private List<Product> FilterCPU(string cpu)
        {
            if (SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyCPU) == null)
            {
                List<string> cpuList = new List<string>
                {
                     cpu
                };
                SessionHelper.SetObjectAsJson(HttpContext.Session, KeyCPU, cpuList);
            }
            else
            {
                List<string> cpuList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyCPU);
                string index = ExistCPU(cpu);
                if (index != "")
                {
                    cpuList.Remove(cpu);
                }
                else
                    cpuList.Add(cpu);
                SessionHelper.SetObjectAsJson(HttpContext.Session, KeyCPU, cpuList);
                if (cpuList.Count == 0)
                {
                    var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
                    return itemLaptop;
                }
            }
            List<string> cpuResult = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyCPU);
            List<Product> result = new List<Product>();
            List<Laptop> resultLaptop = new List<Laptop>();
            foreach (var item in cpuResult)
            {
                var queryCPU = dataContext.Laptops.Where(p => p.LaptopCPU.Contains(item));
                foreach (var itemCPU in queryCPU)
                {
                    resultLaptop.Add(itemCPU);
                }
            }
            CheckConflict(result);
            foreach (var item in resultLaptop)
            {
                Product product = dataContext.Products.FirstOrDefault(p => p.ProductId == item.ProductId);
                result.Add(product);
            }
            return result;
        }
        private List<Product> FilterBrand(string brand)
        {
            if (SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyBrand) == null)
            {
                List<string> brandList = new List<string>
                {
                    brand
                };
                SessionHelper.SetObjectAsJson(HttpContext.Session, KeyBrand, brandList);
            }
            else
            {
                List<string> brandList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyBrand);
                string index = ExistBrand(brand);
                if (index != "")
                    brandList.Remove(brand);
                else
                    brandList.Add(brand);
                SessionHelper.SetObjectAsJson(HttpContext.Session, KeyBrand, brandList);
                if (brandList.Count == 0)
                {
                    var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
                    return itemLaptop;
                }
            }
            List<string> brandResult = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyBrand);
            List<Product> resultTemp = new List<Product>();
            var brandName = dataContext.Brands.ToList();
            foreach (var item in brandResult)
            {
                var queryBrand = dataContext.Products.Where(p => p.Brand.BrandName.Contains(item));
                foreach (var itemBrand in queryBrand)
                {
                    resultTemp.Add(itemBrand);
                }
            }
            CheckConflict(resultTemp);
            var laptop = dataContext.Laptops.ToList();
            List<Product> result = new List<Product>();
            for (int i = 0; i < resultTemp.Count; i++)
            {
                for (int j = 0; j < laptop.Count; j++)
                {
                    if (resultTemp[i].ProductId == laptop[j].ProductId)
                        result.Add(resultTemp[i]);
                }
            }
            return result;
        }
        private List<Product> FilterPrice(string price)
        {
            if (SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyPrice) == null)
            {
                List<string> priceList = new List<string>
                {
                    price
                };
                SessionHelper.SetObjectAsJson(HttpContext.Session, KeyPrice, priceList);
            }
            else
            {
                List<string> priceList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyPrice);
                string index = ExistPrice(price);
                if (index != "")
                    priceList.Remove(price);
                else
                    priceList.Add(price);
                SessionHelper.SetObjectAsJson(HttpContext.Session, KeyPrice, priceList);
                if (priceList.Count == 0)
                {
                    var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
                    return itemLaptop;
                }
            }
            List<string> priceResult = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyPrice);
            List<Product> resultTemp = new List<Product>();
            List<Product> queryPrice = new List<Product>();
            foreach (var item in priceResult)
            {
                if (item == "20tr")
                {
                    queryPrice = dataContext.Products.Where(p => p.ProductPrice >= 20000000 && p.ProductPrice <= 30000000).ToList();
                }
                if (item == "60tr")
                {
                    queryPrice = dataContext.Products.Where(p => p.ProductPrice >= 60000000 && p.ProductPrice <= 70000000).ToList();
                }
                if (item == "120tr")
                {
                    queryPrice = dataContext.Products.Where(p => p.ProductPrice >= 120000000).ToList();
                }
                if (queryPrice != null)
                {
                    foreach (var itemPrice in queryPrice)
                    {
                        resultTemp.Add(itemPrice);
                    }
                }
            }
            CheckConflict(resultTemp);
            var laptop = dataContext.Laptops.ToList();
            List<Product> result = new List<Product>();
            for (int i = 0; i < resultTemp.Count; i++)
            {
                for (int j = 0; j < laptop.Count; j++)
                {
                    if (resultTemp[i].ProductId == laptop[j].ProductId)
                        result.Add(resultTemp[i]);
                }
            }
            return result;
        }
        public IActionResult DeleteFilter()
        {
            List<string> cpuList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyCPU);
            List<string> brandList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyBrand);
            List<string> priceResult = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyPrice);
            SessionHelper.ClearSession(HttpContext.Session);
            var itemLaptop = dataContext.Products.Where(p => p.CategoryId == 1).ToList();
            return View("Index",itemLaptop);
        }
        private string ExistCPU(string cpu)
        {
            List<string> cpuList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyCPU);
            for (int i = 0; i < cpuList.Count; i++)
            {
                if (cpuList[i] == cpu)
                    return cpu;
            }
            return "";
        }
        private string ExistPrice(string price)
        {
            List<string> priceList = SessionHelper.GetObjectFromJson<List<string>>(HttpContext.Session, KeyPrice);
            for (int i = 0; i < priceList.Count; i++)

PCWeb/Areas/Admin/Views/Component/Add.cshtml
@model PCWeb.Models.Name.PCComponent
@{
    ViewData["Title"] = "Thêm linh kiện";
}
<h2 class="text-center">Phân loại linh kiện</h2>
<hr />
<div class="col-lg-10">
    <form asp-action="Add" asp-controller="Component" method="post">
        <div class="form-group row">
            <label asp-for="Product.ProductName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-6">
                <select asp-for="ProductId" class="form-control"
                        asp-items="@ViewBag.Selected">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ComponentCategory.ComponentCategoryName" class="col-sm-3 col-form-label"></label>
            <div class="col-sm-6">
                <select asp-for="ComponentCategoryId" class="form-control"
                        asp-items="@ViewBag.Category">
                </select>
            </div>
        </div>
        <div class="form-group row col-sm-3">
            <input type="submit" value="Thêm" class="btn btn-primary" />
        </div>
    </form>
    <div>
        <a asp-action="Index" class="btn btn-primary">Quay lại danh sách</a>
    </div>
</div>

PCWeb/Areas/Admin/Views/Component/Category.cshtml
@{
    ViewData["Title"] = "Linh kiện";
}
<h2 class="text-center">Linh kiện</h2>
<div class="row">
    <table class="table">
        <tr>
            <th class="border-right">
                <a class="btn btn-info button-component float-right" asp-action="Index" asp-controller="CPU" asp-area="Admin">CPU</a>
            </th>
            <td>
                <a class="btn btn-info button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Mainboard</a>
            </td>
        </tr>
        <tr>
            <th class="border-right">
                <a class="btn btn-info float-right button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Ram</a>
            </th>
            <td>
                <a class="btn btn-info button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Card đồ họa</a>
            </td>
        </tr>
        <tr>
            <th class="border-right">
                <a class="btn btn-info float-right button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Ổ lưu trữ</a>
            </th>
            <td>
                <a class="btn btn-info button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Nguồn</a>
            </td>
        </tr>
        <tr>
            <th class="border-right">
                <a class="btn btn-info float-right button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Tản nhiệt</a>
            </th>
            <td>
                <a class="btn btn-info button-component" asp-action="Index" asp-controller="CPU" asp-area="Admin">Case máy tính</a>
            </td>
        </tr>
    </table>
</div>

PCWeb/Areas/Admin/Views/Component/Delete.cshtml
@model PCWeb.Models.Name.PCComponent
@{
    ViewData["Title"] = "Xóa";
}
<h3>Bạn có chắc chắn xóa linh kiện này không?</h3>
<br />
<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Xóa" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-info">Quay về danh sách</a>
    </form>
</div>

PCWeb/Areas/Admin/Views/Component/Index.cshtml
@using PCWeb.Models.Name
@{
    ViewData["Title"] = "Linh kiện";
}
@model List<PCComponent>
<h2 class="text-md-center">Linh kiện </h2>
<br />
<form class="row" asp-controller="Laptop" asp-action="Index" asp-area="Admin" method="get">
    <div class="col-sm-2 text-right form-group">
        <label class="col-form-label">
            Tìm kiếm:
        </label>
    </div>
    <div class="form-group col-sm-2">
        <select name="name" class="form-control">
            <option value="all">All</option>
            @*@foreach (var item in ViewBag.Category)
            {
                <option value="@item.LaptopCategoryName">@item.LaptopCategoryName</option>
            }*@
        </select>
        @*<span asp-validation-for="@Model[0].LaptopCategoryId" class="text-danger"></span>*@
    </div>
    <div class="col-sm-6 form-group">
        <input type="text" class="input-width form-control mr-sm-2" name="search" placeholder="Nhập tên linh kiện">
    </div>
    <div class="col-sm-2 form-group">
        <button type="submit" class="btn btn-success">Tìm</button>
    </div>
</form>
<br />
<h3>Số lượng sản phẩm: @Model.Count</h3>
<p><a class="btn btn-primary" asp-controller="Component" asp-action="Add">Thêm</a></p>
<table class="table">
    <thead>
        <tr>
            <th>STT</th>
            <th>Tên Linh kiện</th>
            <th>Loại linh kiện</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            int i = 1;
            @foreach (var item in Model)
            {
                <tr>
                    <td>@(i++)</td>
                    <td>@item.Product.ProductName</td>
                    <td>@item.ComponentCategory.ComponentCategoryName</td>
                    <td>
                        <a class="btn btn-outline-danger" asp-area="Admin" asp-controller="Component" asp-action="Delete" asp-route-id="@item.PCComponentId">Xóa</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>